server:
  port: 1234

spring:
  mail:
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            required: true
            enabled: true
    host: smtp.gmail.com
    username: res.pswd.attractor@gmail.com
    password: udbjmooacwidosgt
    port: 587

  mvc:
    static-path-pattern: static/**
#    log-request-details: false
  datasource:
    url: jdbc:h2:./db/job_search;AUTO_SERVER=TRUE
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver
  liquibase:
    change-log: classpath:/db/changelog/master.yaml
  freemarker:
    expose-session-attributes: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: info
    org:
      springframework:
        security: debug
      hibernate:
        stat: debug
    sql: trace
    web: debug
  file:
     name: logs/spring.log
