server:
  port: 1234

spring:
  datasource:
    url: jdbc:h2:./db/job_search;AUTO_SERVER=TRUE
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver
  liquibase:
    change-log: classpath:/db/changelog/master.yaml
logging:
  level:
     root: info
     org:
       springframework:
         security: debug
  file:
     name: logs/spring.log
